### ISSUE TITLE
Using SmObjectFactory in WebAPI project

### ISSUE THREAD

**Issue by SirwanAfifi** [VahidN/Dependency-Injection-Samples#1]
When I use `SmObjectFactory` in my [WebAPI](http://www.dotnettips.info/courses/topic/5/3697d84b-8c79-4722-875f-a35920fe88ba) project I get this error:
`type StructureMapHttpControllerActivator must derive from IHttpControllerActivator. Parameter name: service`

I also used `SmObjectFactory` in `WebApiConfig.cs` this way:

```
var container = SmObjectFactory.Container;  
GlobalConfiguration.Configuration.Services.Replace(  
     typeof(IHttpControllerActivator), new StructureMapHttpControllerActivator(container));  
// Web API routes  
config.MapHttpAttributeRoutes();  
config.Routes.MapHttpRoute(  
     name: "DefaultApi",  
     routeTemplate: "api/{controller}/{id}",  
     defaults: new { id = RouteParameter.Optional }  
);
```

Any idea?
Thanks.

**Comment by VahidN** [comment]
[StructureMapHttpControllerActivator](https://github.com/VahidN/Dependency-Injection-Samples/blob/master/DI08/DI08/Core/StructureMapHttpControllerActivator.cs) is derived from IHttpControllerActivator. 
Also you can find its improved version using [SmObjectFactory](https://github.com/VahidN/Dependency-Injection-Samples/tree/master/DI08/DI08/App_Start)  here: [DI08](https://github.com/VahidN/Dependency-Injection-Samples/tree/master/DI08/) (It's tested and works)
