### ISSUE TITLE
How to resolve Microsoft.AspNet.SignalR.Messaging.IMessageBus?

### ISSUE THREAD

**Issue by SirwanAfifi** [VahidN/Dependency-Injection-Samples#2]
Hi, I'm using custom dependency resolver for my SignalR application, I have also attached the new resolver to my `GlobalHost.DependencyResolver`. It works like a charm in SignalR version 2.1.2 But after upgrading to SignalR version 2.2.0, It gives me this error:

```
No default Instance is registered and cannot be automatically determined for type 'Microsoft.AspNet.SignalR.Messaging.IMessageBus'
There is no configuration specified for Microsoft.AspNet.SignalR.Messaging.IMessageBus
1.) new AckSubscriber(*Default of IMessageBus*, *Default of IAckHandler*)
2.) Microsoft.AspNet.SignalR.Infrastructure.AckSubscriber
3.) Instance of Microsoft.AspNet.SignalR.Infrastructure.AckSubscriber
4.) Container.GetInstance(Microsoft.AspNet.SignalR.Infrastructure.AckSubscriber)
```

As you can see, the resolver can't resolve [IMessageBus](https://msdn.microsoft.com/en-us/library/microsoft.aspnet.signalr.messaging.imessagebus%28v=vs.118%29.aspx) beacase it needs an implementation for it. Which implementation Should I provide for this interface?
The question on [StackOverFlow](http://stackoverflow.com/questions/31793209/signalr-resolving-imessagebus)

**Comment by VahidN** [comment]
[This updated sample](https://github.com/VahidN/SignalR-Samples/blob/master/SignalR02/SignalR02/Utils/StructureMapDependencyResolver.cs) uses v2.2.0.
